apps/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', view=views.home, name='index'),
    path('publications', view=views.get_publications, name='publications'),
    path('publications/<int:pk>', view=views.get_publication, name='publication')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.blog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

from apps.users.models import User


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Publication(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='publications'
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name='publications'
    )
    tags = models.ManyToManyField(
        Tag, related_name='publications', blank=True
    )

    image = models.ImageField(upload_to='publications', null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name='Title')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, UserManager


class CustomUserManager(UserManager):

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_active', True)
        if extra_fields.get('is_active') is not True:
            raise ValueError('Superuser must have is_active=True.')

        return super().create_superuser(username, email, password, **extra_fields)


class User(AbstractUser):

    first_name = None
    last_name = None

    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='avatars/', default='default/avatar.png')
    is_active = models.BooleanField(default=False)

    objects = CustomUserManager()

apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from .models import Publication, Category, Tag


def home(request):

    return render(request=request, template_name='index.html')


def get_publications(request):
    publications = Publication.objects.all().order_by('-created')
    paginator = Paginator(object_list=publications, per_page=12)

    page = request.GET.get('page', 1)
    publications = paginator.get_page(number=page)    

    context = {
        'publications': publications
    }
    return render(request=request, template_name='publications.html', context=context)


def get_publication(request, pk):

    publication = get_object_or_404(Publication, id=pk)

    context = {
        'publication': publication
    }
    return render(request, template_name='publication.html', context=context)

apps/users/views.py
from django.shortcuts import render

# Create your views here.

apps/blog/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  <section class="blog-posts">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">

              {% for publication in context_recent_publications %}

              <div class="col-lg-12">
                <div class="blog-post">
                  <div class="blog-thumb">
                    {% if publication.image %}
                    <a href="{% url 'blog:publication' pk=publication.id %}">
                      <img src="{{ publication.image.url }}" alt="">
                    </a>
                    {% endif %}
                  </div>
                  <div class="down-content">
                    <span>{{ publication.category.name }}</span>
                    <a href="{% url 'blog:publication' pk=publication.id %}"><h4>{{ publication.name }}</h4></a>
                    <ul class="post-info">
                      <li><a href="#">{{ publication.author.full_name }}</a></li>
                      <li><a href="#">{{ publication.created|date:"F d, Y" }}</a></li>
                      <li><a href="#">0 Comments</a></li>
                    </ul>
                    <p>{{ publication.text|slice:":500" }}...</p>
                    <div class="post-options">
                      <div class="row">
                        <div class="col-6">
                          <ul class="post-tags">
                            <li><i class="fa fa-tags"></i></li>
                            {% for tag in publication.tags.all %}
                            <li><a href="#">{{ tag.name }}</a></li>
                            {% endfor %}
                          </ul>
                        </div>
                        <div class="col-6">
                          <ul class="post-share">
                            <li><i class="fa fa-share-alt"></i></li>
                            <li><a href="#">Facebook</a>,</li>
                            <li><a href="#"> Twitter</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}

              <div class="col-lg-12">
                <div class="main-button">
                  <a href="{% url 'blog:publications' %}">View All Posts</a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% include 'sidebar.html' %}
      </div>
    </div>
  </section>
{% endblock %}

apps/blog/templates/publication.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="blog-posts grid-system">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">
              <div class="col-lg-12">
                <div class="blog-post">
                    <div class="blog-thumb">
                      {% if publication.image %}
                      <img src="{{ publication.image.url }}" alt="">
                      {% endif %}
                    </div>
                    <div class="down-content">
                      <span>{{ publication.category.name }}</span>
                      <a href="post-details.html"><h4>{{ publication.name }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ publication.author.full_name }}</a></li>
                        <li><a href="#">{{ publication.created|date:"F d, Y" }}</a></li>
                      </ul>
                      <p>{{ publication.text }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              {% for tag in publication.tags.all %}
                              <li><a href="#">{{ tag.name }}</a></li>
                              {% endfor %}
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item comments">
                  <div class="sidebar-heading">
                    <h2>4 comments</h2>
                  </div>
                  <div class="content">
                    <ul>
                      <li>
                        <div class="author-thumb">
                          <img src="assets/images/comment-author-01.jpg" alt="">
                        </div>
                        <div class="right-content">
                          <h4>Charles Kate<span>May 16, 2020</span></h4>
                          <p>Fusce ornare mollis eros. Duis et diam vitae justo fringilla condimentum eu quis leo. Vestibulum id turpis porttitor sapien facilisis scelerisque. Curabitur a nisl eu lacus convallis eleifend posuere id tellus.</p>
                        </div>
                      </li>
                      <li class="replied">
                        <div class="author-thumb">
                          <img src="assets/images/comment-author-02.jpg" alt="">
                        </div>
                        <div class="right-content">
                          <h4>Thirteen Man<span>May 20, 2020</span></h4>
                          <p>In porta urna sed venenatis sollicitudin. Praesent urna sem, pulvinar vel mattis eget.</p>
                        </div>
                      </li>
                      <li>
                        <div class="author-thumb">
                          <img src="assets/images/comment-author-03.jpg" alt="">
                        </div>
                        <div class="right-content">
                          <h4>Belisimo Mama<span>May 16, 2020</span></h4>
                          <p>Nullam nec pharetra nibh. Cras tortor nulla, faucibus id tincidunt in, ultrices eget ligula. Sed vitae suscipit ligula. Vestibulum id turpis volutpat, lobortis turpis ac, molestie nibh.</p>
                        </div>
                      </li>
                      <li class="replied">
                        <div class="author-thumb">
                          <img src="assets/images/comment-author-02.jpg" alt="">
                        </div>
                        <div class="right-content">
                          <h4>Thirteen Man<span>May 22, 2020</span></h4>
                          <p>Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo.</p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="sidebar-item submit-comment">
                  <div class="sidebar-heading">
                    <h2>Your comment</h2>
                  </div>
                  <div class="content">
                    <form id="comment" action="#" method="post">
                      <div class="row">
                        <div class="col-md-6 col-sm-12">
                          <fieldset>
                            <input name="name" type="text" id="name" placeholder="Your name" required="">
                          </fieldset>
                        </div>
                        <div class="col-md-6 col-sm-12">
                          <fieldset>
                            <input name="email" type="text" id="email" placeholder="Your email" required="">
                          </fieldset>
                        </div>
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                            <input name="subject" type="text" id="subject" placeholder="Subject">
                          </fieldset>
                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <textarea name="message" rows="6" id="message" placeholder="Type your comment" required=""></textarea>
                          </fieldset>
                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button">Submit</button>
                          </fieldset>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        {% include 'sidebar.html' %}
      </div>
    </div>
  </section>

{% endblock %}

apps/blog/templates/publications.html
{% extends 'base.html' %}

{% load static %}


{% block content %}

<section class="blog-posts grid-system">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="all-blog-posts">
            <div class="row">

             {% for publication in publications %}
              <div class="col-lg-6">
                <div class="blog-post">
                  <div class="blog-thumb">
                    {% if publication.image %}
                    <a href="{% url 'blog:publication' pk=publication.id %}">
                        <img src="{{ publication.image.url }}" alt="">
                    </a>
                    {% endif %}
                  </div>
                  <div class="down-content">
                    <span>{{ publication.category.name }}</span>
                    <a href="{% url 'blog:publication' pk=publication.id %}"><h4>{{ publication.name }}</h4></a>
                    <ul class="post-info">
                      <li><a href="#">{{ publication.author.full_name }}</a></li>
                      <li><a href="#">{{ publication.created|date:"F d, Y" }}</a></li>
                      <li><a href="#">0 Comments</a></li>
                    </ul>
                    <p>{{ publication.text|slice:":200" }}...</p>
                    <div class="post-options">
                      <div class="row">
                        <div class="col-lg-12">
                          <ul class="post-tags">
                            <li><i class="fa fa-tags"></i></li>
                            {% for tag in publication.tags.all %}
                            <li><a href="#">{{ tag.name }}</a></li>
                            {% endfor %}
                          </ul>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
              <div class="col-lg-12">
                <ul class="page-numbers">

                {% if publications.number != 1 %}
                  <li><a href="?page=1"><i class="fa fa-angle-double-left"></i></a></li>
                {% endif %}

                {% if publications.has_previous %}
                  <li><a href="?page={{ publications.previous_page_number }}"><i class="fa fa-angle-left"></i></a></li>
                {% endif %}  

                  <li class="active"><a href="" style="width: 100px;">{{ publications.number }} of {{ publications.paginator.num_pages }}</a></li>
                  
                {% if publications.has_next %}
                  <li><a href="?page={{ publications.next_page_number }}"><i class="fa fa-angle-right"></i></a></li>
                {% endif %}
                
                {% if publications.number != publications.paginator.num_pages %}
                  <li><a href="?page={{ publications.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a></li>
                {% endif %}

                </ul>
              </div>
            </div>
          </div>
        </div>
        {% include 'sidebar.html' %}
      </div>
    </div>
  </section>

{% endblock %}

templates/banner.html
{% load static %}

<div class="main-banner header-text">
    <div class="container-fluid">
      <div class="owl-banner owl-carousel">
        {% for publication in publications %}

        <div class="item">
        {% if publication.image %}
          <img src="{{ publication.image.url }}" alt="">
        {% else %}
            <img src="{% static 'assets/images/blog-thumb-02.jpg' %}" alt="">
        {% endif %}
          <div class="item-content">
            <div class="main-content">
              <div class="meta-category">
                <span>{{ publication.category.name }}</span>
              </div>
              <a href="post-details.html"><h4>{{ publication.name }}</h4></a>
              <ul class="post-info">
                <li><a href="#">{{ publication.author.full_name }}</a></li>
                <li><a href="#">{{ publication.created|date:"F d, Y" }}</a></li>
                <li><a href="#">0 Comments</a></li>
              </ul>
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>
  </div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="TemplateMo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap" rel="stylesheet">

    <title>Stand CSS Blog by TemplateMo</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--

TemplateMo 551 Stand Blog

https://templatemo.com/tm-551-stand-blog

-->
  </head>

  <body>

    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="{% url 'blog:index' %}"><h2>Stand Blog<em>.</em></h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'blog:index' %}">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="about.html">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:publications' %}">Blog Entries</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="post-details.html">Post Details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact Us</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>


    <div class="main-banner header-text">
      <div class="container-fluid">
        <div class="owl-banner owl-carousel">
        </div>
      </div>
    </div>

    {% block content %}

    {% endblock %}



    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Behance</a></li>
                <li><a href="#">Linkedin</a></li>
                <li><a href="#">Dribbble</a></li>
              </ul>
            </div>
            <div class="col-lg-12">
              <div class="copyright-text">
                <p>Copyright 2020 Stand Blog Co.
                      
                   | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
              </div>
            </div>
          </div>
        </div>
      </footer>
  
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  
      <!-- Additional Scripts -->
      <script src="{% static 'assets/js/custom.js' %}"></script>
      <script src="{% static 'assets/js/owl.js' %}"></script>
      <script src="{% static 'assets/js/slick.js' %}"></script>
      <script src="{% static 'assets/js/isotope.js' %}"></script>
      <script src="{% static 'assets/js/accordions.js' %}"></script>
  
      <script language = "text/Javascript"> 
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t){                   //declaring the array outside of the
        if(! cleared[t.id]){                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value='';         // with more chance of typos
            t.style.color='#fff';
            }
        }
      </script>
  
    </body>
  </html>

templates/sidebar.html
{% load static %}

<div class="col-lg-4">
    <div class="sidebar">
      <div class="row">
        <div class="col-lg-12">
          <div class="sidebar-item search">
            <form id="search_form" name="gs" method="GET" action="#">
              <input type="text" name="q" class="searchText" placeholder="type to search..." autocomplete="on">
            </form>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item recent-posts">
            <div class="sidebar-heading">
              <h2>Recent Posts</h2>
            </div>
            <div class="content">
              <ul>
                {% for publication in context_recent_publications %}
                <li><a href="post-details.html">
                  <h5>{{ publication.name }}</h5>
                  <span>{{ publication.created|date:"F d, Y" }}</span>
                </a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item categories">
            <div class="sidebar-heading">
              <h2>Categories</h2>
            </div>
            <div class="content">
              <ul>
                {% for category in context_categories %}
                <li><a href="#">- {{ category.name }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="sidebar-item tags">
            <div class="sidebar-heading">
              <h2>Tag Clouds</h2>
            </div>
            <div class="content">
              <ul>
                {% for tag in context_tags %}
                <li><a href="#">{{ tag.name }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>